name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aiohttp=3.9.5=py39hd1e30aa_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.16=h79b3bcb_6
  - aws-c-cal=0.6.10=hb29e0c7_1
  - aws-c-common=0.9.13=hd590300_0
  - aws-c-compression=0.2.18=hecc5fa9_1
  - aws-c-event-stream=0.4.2=hf9b2f7b_4
  - aws-c-http=0.8.1=h5d7533a_5
  - aws-c-io=0.14.5=h50678d4_1
  - aws-c-mqtt=0.10.2=hf479d2b_4
  - aws-c-s3=0.5.2=h4ad9680_0
  - aws-c-sdkutils=0.1.15=hecc5fa9_1
  - aws-checksums=0.1.18=hecc5fa9_1
  - aws-crt-cpp=0.26.2=h19f5d62_7
  - aws-sdk-cpp=1.11.267=h5606698_1
  - brotli-python=1.1.0=py39h3d6467e_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cuda-cudart=12.4.127=hd3aeb46_0
  - cuda-cudart_linux-64=12.4.127=h59595ed_0
  - cuda-nvrtc=12.4.127=hd3aeb46_1
  - cuda-nvtx=12.4.127=h59595ed_1
  - cuda-version=12.4=h3060b56_3
  - cudnn=8.9.7.29=h092f7fd_3
  - datasets=2.19.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.14.0=pyhd8ed1ab_0
  - frozenlist=1.4.1=py39hd1e30aa_0
  - fsspec=2024.3.1=pyhca7485f_0
  - gflags=2.2.2=he1b5a44_1004
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glog=0.7.0=hed5481d_0
  - gmp=6.3.0=h59595ed_1
  - gmpy2=2.1.5=py39h03b5d36_0
  - huggingface_hub=0.23.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libarrow=15.0.0=h17fe1ab_6_cpu
  - libarrow-acero=15.0.0=h59595ed_6_cpu
  - libarrow-dataset=15.0.0=h59595ed_6_cpu
  - libarrow-flight=15.0.0=hdc44a87_6_cpu
  - libarrow-flight-sql=15.0.0=hfbc7f12_6_cpu
  - libarrow-gandiva=15.0.0=h308e607_6_cpu
  - libarrow-substrait=15.0.0=hfbc7f12_6_cpu
  - libblas=3.9.0=22_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=22_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.4.5.8=hd3aeb46_1
  - libcufft=11.2.1.3=hd3aeb46_1
  - libcurand=10.3.5.147=hd3aeb46_1
  - libcurl=8.7.1=hca28451_0
  - libcusolver=11.6.1.9=hd3aeb46_1
  - libcusparse=12.3.1.170=hd3aeb46_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_6
  - libgfortran-ng=13.2.0=h69a702a_6
  - libgfortran5=13.2.0=h43f5ff8_6
  - libgomp=13.2.0=h77fa898_6
  - libgoogle-cloud=2.17.0=h31df0ca_2
  - libgoogle-cloud-storage=2.17.0=hc7a4891_2
  - libgrpc=1.60.1=h74775cd_0
  - libhwloc=2.10.0=default_h2fb2949_1000
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=22_linux64_openblas
  - libllvm16=16.0.6=hb3ce162_3
  - libmagma=2.7.2=h173bb3b_2
  - libmagma_sparse=2.7.2=h173bb3b_3
  - libnghttp2=1.58.0=h47da74e_1
  - libnl=3.9.0=hd590300_0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.4.127=hd3aeb46_1
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libparquet=15.0.0=h352af49_6_cpu
  - libprotobuf=4.25.1=hf27288f_2
  - libre2-11=2023.09.01=h7a70373_1
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_6
  - libthrift=0.19.0=hb90f79a_1
  - libtorch=2.1.2=cuda120_h2aa5df7_303
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.6=h232c23b_2
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=18.1.4=ha31de31_0
  - lz4-c=1.9.4=hcb278e6_0
  - magma=2.7.2=h51420fd_3
  - markupsafe=2.1.5=py39hd1e30aa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.2.0=h84fe81f_50496
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_1
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multidict=6.0.5=py39hd1e30aa_0
  - multiprocess=0.70.16=py39hd1e30aa_0
  - nccl=2.21.5.1=h3a97aeb_0
  - ncurses=6.4.20240210=h59595ed_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=1.26.4=py39h474f0d3_0
  - openssl=3.3.0=hd590300_0
  - orc=1.9.2=h7829240_1
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py39hddac248_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - protobuf=4.25.1=py39h60f6b12_0
  - psutil=5.9.8=py39hd1e30aa_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=15.0.0=py39h6925388_6_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.19=h0755675_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python-xxhash=3.4.1=py39hd1e30aa_0
  - python_abi=3.9=4_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py39hd1e30aa_1
  - rdma-core=51.0=hd3aeb46_0
  - re2=2023.09.01=h7f4b329_1
  - readline=8.2=h8228510_1
  - regex=2024.4.28=py39hd3abc70_0
  - requests=2.31.0=pyhd8ed1ab_0
  - s2n=1.4.5=h06160fa_0
  - safetensors=0.4.3=py39h9fdd4d6_0
  - scikit-learn=1.4.2=py39ha22ef79_0
  - scipy=1.13.0=py39haf93ffa_1
  - sentry-sdk=2.0.1=pyhd8ed1ab_0
  - setproctitle=1.3.3=py39hd1e30aa_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=hdb0a2a9_1
  - sqlite=3.45.3=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.12.0=h00ab1b0_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tokenizers=0.19.1=py39hc62d755_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - transformers=4.40.1=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucx=1.15.0=hda83522_8
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xxhash=0.8.2=hd590300_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py39hd1e30aa_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.16.0
      - comm==0.2.2
      - debugpy==1.8.1
      - defusedxml==0.7.1
      - fastjsonschema==2.19.1
      - fqdn==1.5.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - importlib-metadata==7.1.0
      - ipykernel==6.29.4
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.1
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - jupyterlab-widgets==3.0.10
      - lightning==2.3.0.dev0
      - lightning-utilities==0.11.2
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.1.3
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pillow==10.3.0
      - platformdirs==4.2.1
      - prometheus-client==0.20.0
      - pycparser==2.22
      - pyparsing==3.1.2
      - python-json-logger==2.0.7
      - pytorch-lightning==2.2.4
      - pyzmq==26.0.3
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - rdkit==2023.9.5
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.5
      - terminado==0.18.1
      - tinycss2==1.3.0
      - tomli==2.0.1
      - torch==2.3.0
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18+pt23cu121
      - torchmetrics==1.4.0.post0
      - torchvision==0.18.0
      - tornado==6.4
      - triton==2.3.0
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - wandb==0.17.0
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.10
      - zipp==3.18.1
prefix: /home/alexeyorlov53/anaconda3/envs/myenv
